### ISSUE TITLE
Can't use 'd' to switch to disassembly/mixed view or set breakpoints

### ISSUE THREAD

**Issue by sonictk** [ftilde/ugdb#14] opened 2020-03-06 00:45 UTC
Hi, just found this project. It's pretty great so far!

I'm encountering an issue with trying to get the split source/disassembly view, or even just getting the disassembly view to show up. If I hit 'd' while in the source view, nothing happens. I tried setting RUST_LOG to `all` in my environment and then running ugdb, but didn't see any warning messages. It's weird that I am able to view the source, but not able to view the disassembly for it.

I also can't set a breakpoint using Space in the source view: whenever I try, I keep getting the error message that gdb is busy, even though I can go to the gdb terminal and type `b` and get a breakpoint set for me instead (which the source window then updates to match)

I'm using the build of ugdb that is available when installed via cargo (0.1.6). 

Could you advise what I might be missing in order to get it working? I'm not that familiar with Rust, but I did see the code surrounding activating the split view and it looks like you'll attempt to log a warning if something goes wrong, but I don't see any such warning output in my terminal.

Thanks again for this cool app!

**Comment by ftilde** [comment] 2020-03-06 20:43
Hey!

I suspect both problems are due to the fact that ugdb starts gdb in "synchronous mode" which means that we cannot communicate with gdb when the debuggee is running. If you want to set a breakpoint or disassemble the current source file you will have to stop the process using `Ctrl-C` in the command window first. Since this behaviour is non-obvious (as I realize now) I've also added a section explaining it to the readme.

Does this answer your question/solve your problem?

**Comment by sonictk** [comment] 2020-03-06 23:04
Hi @ftilde:

Thanks for the response. Unfortunately I don't think that's the issue, since the process is halted when I'm attempting to set a breakpoint. I can even run the application halted (`start` in gdb), and it will still say that gdb is busy and that I can't insert a breakpoint.

I tried hitting ctrl-c while in gdb and that, as expected, printed 'Quit', but it still made no difference: I couldn't insert breakpoints in the source window or switch to disassembly view either. FWIW I tried this on my Ubuntu 18.04 LTS install at home last night as well since our CentOS 7 install at work is pretty ancient, but I had the same problem.

**Comment by ftilde** [comment] 2020-03-07 12:03
Alright, in this case, can you have a look at the log files (should be located in `/tmp` unless you specified `--log_dir` and be named something like `ugdb_<datetime>.log`) and post them here?

**Comment by sonictk** [comment] 2020-03-09 18:50
Hi @ftilde:

Here's the log file for a simple test application:

```
INFO [ugdb::gdbmi::output] =thread-group-added,id="i1"
INFO [ugdb::gdbmi::output] ~"GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-100.el7_4.1\n"
INFO [ugdb::gdbmi::output] ~"Copyright (C) 2013 Free Software Foundation, Inc.\n"
INFO [ugdb::gdbmi::output] ~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
INFO [ugdb::gdbmi::output] ~"This GDB was configured as \"x86_64-redhat-linux-gnu\".\nFor bug reporting instructions, please see:\n"
INFO [ugdb::gdbmi::output] ~"<http://www.gnu.org/software/gdb/bugs/>...\n"
INFO [ugdb::gdbmi::output] =cmd-param-changed,param="disassembly-flavor",value="intel"
INFO [ugdb::gdbmi::output] =cmd-param-changed,param="print pretty",value="on"
INFO [ugdb::gdbmi::output] ~"Reading symbols from /home/yliangsiew/Git/experiments/custom_malloc/build/custom_malloc..."
INFO [ugdb::gdbmi::output] ~"done.\n"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::tui::tui] unhandled async_record: [Notify, Other("thread-group-added")] {
  "id": "i1"
}
INFO [ugdb::tui::tui] unhandled async_record: [Notify, CmdParamChanged] {
  "param": "disassembly-flavor",
  "value": "intel"
}
INFO [ugdb::tui::tui] unhandled async_record: [Notify, CmdParamChanged] {
  "param": "print pretty",
  "value": "on"
}
INFO [ugdb::gdbmi] Writing msg 1-interpreter-exec console "start"

INFO [ugdb::gdbmi::output] ~"Temporary breakpoint 1 at 0x400a95: file /home/yliangsiew/Git/experiments/custom_malloc/main.c, line 8.\n"
INFO [ugdb::gdbmi::output] =breakpoint-created,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x0000000000400a95",func="main",file="/home/yliangsiew/Git/experiments/custom_malloc/main.c",fullname="/home/yliangsiew/Git/experiments/custom_malloc/main.c",line="8",thread-groups=["i1"],times="0",original-location="main"}
INFO [ugdb::gdbmi::output] ~"Starting program: /home/yliangsiew/Git/experiments/custom_malloc/build/./custom_malloc \n"
INFO [ugdb::gdbmi::output] =thread-group-started,id="i1",pid="9273"
INFO [ugdb::gdbmi::output] =thread-created,id="1",group-id="i1"
INFO [ugdb::gdbmi::output] 1^running
INFO [ugdb::gdbmi::output] *running,thread-id="all"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::tui::tui] unhandled async_record: [Notify, Thread(GroupStarted)] {
  "id": "i1",
  "pid": "9273"
}
INFO [ugdb::tui::tui] unhandled async_record: [Notify, Thread(Created)] {
  "id": "1",
  "group-id": "i1"
}
INFO [ugdb::tui::tui] unhandled async_record: [Exec, Other("running")] {
  "thread-id": "all"
}
INFO [ugdb::gdbmi::output] =library-loaded,id="/lib64/ld-linux-x86-64.so.2",target-name="/lib64/ld-linux-x86-64.so.2",host-name="/lib64/ld-linux-x86-64.so.2",symbols-loaded="0",thread-group="i1"
INFO [ugdb::tui::tui] unhandled async_record: [Notify, LibraryLoaded] {
  "id": "/lib64/ld-linux-x86-64.so.2",
  "target-name": "/lib64/ld-linux-x86-64.so.2",
  "host-name": "/lib64/ld-linux-x86-64.so.2",
  "symbols-loaded": "0",
  "thread-group": "i1"
}
INFO [ugdb::gdbmi::output] &"warning: the debug information found in \"/usr/lib/debug//lib64/ld-2.17.so.debug\" does not match \"/lib64/ld-linux-x86-64.so.2\" (CRC mismatch).\n"
INFO [ugdb::gdbmi::output] &"\n"
INFO [ugdb::gdbmi::output] &"warning: the debug information found in \"/usr/lib/debug/usr/lib64/ld-2.17.so.debug\" does not match \"/lib64/ld-linux-x86-64.so.2\" (CRC mismatch).\n"
INFO [ugdb::gdbmi::output] &"\n"
INFO [ugdb::gdbmi::output] &"warning: the debug information found in \"/usr/lib/debug//usr/lib64/ld-2.17.so.debug\" does not match \"/lib64/ld-linux-x86-64.so.2\" (CRC mismatch).\n"
INFO [ugdb::gdbmi::output] &"\n"
INFO [ugdb::gdbmi::output] &"warning: the debug information found in \"/usr/lib/debug/usr/lib64//ld-2.17.so.debug\" does not match \"/lib64/ld-linux-x86-64.so.2\" (CRC mismatch).\n"
INFO [ugdb::gdbmi::output] &"\n"
INFO [ugdb::gdbmi::output] =library-loaded,id="/lib64/libpthread.so.0",target-name="/lib64/libpthread.so.0",host-name="/lib64/libpthread.so.0",symbols-loaded="0",thread-group="i1"
INFO [ugdb::gdbmi::output] =library-loaded,id="/lib64/libc.so.6",target-name="/lib64/libc.so.6",host-name="/lib64/libc.so.6",symbols-loaded="0",thread-group="i1"
INFO [ugdb::tui::tui] unhandled async_record: [Notify, LibraryLoaded] {
  "id": "/lib64/libpthread.so.0",
  "target-name": "/lib64/libpthread.so.0",
  "host-name": "/lib64/libpthread.so.0",
  "symbols-loaded": "0",
  "thread-group": "i1"
}
INFO [ugdb::tui::tui] unhandled async_record: [Notify, LibraryLoaded] {
  "id": "/lib64/libc.so.6",
  "target-name": "/lib64/libc.so.6",
  "host-name": "/lib64/libc.so.6",
  "symbols-loaded": "0",
  "thread-group": "i1"
}
INFO [ugdb::gdbmi::output] &"warning: the debug information found in \"/usr/lib/debug//lib64/libpthread-2.17.so.debug\" does not match \"/lib64/libpthread.so.0\" (CRC mismatch).\n"
INFO [ugdb::gdbmi::output] &"\n"
INFO [ugdb::gdbmi::output] &"warning: the debug information found in \"/usr/lib/debug/usr/lib64/libpthread-2.17.so.debug\" does not match \"/lib64/libpthread.so.0\" (CRC mismatch).\n"
INFO [ugdb::gdbmi::output] &"\n"
INFO [ugdb::gdbmi::output] &"warning: the debug information found in \"/usr/lib/debug//usr/lib64/libpthread-2.17.so.debug\" does not match \"/lib64/libpthread.so.0\" (CRC mismatch).\n"
INFO [ugdb::gdbmi::output] &"\n"
INFO [ugdb::gdbmi::output] &"warning: the debug information found in \"/usr/lib/debug/usr/lib64//libpthread-2.17.so.debug\" does not match \"/lib64/libpthread.so.0\" (CRC mismatch).\n"
INFO [ugdb::gdbmi::output] &"\n"
INFO [ugdb::gdbmi::output] ~"[Thread debugging using libthread_db enabled]\n"
INFO [ugdb::gdbmi::output] ~"Using host libthread_db library \"/lib64/libthread_db.so.1\".\n"
INFO [ugdb::gdbmi::output] &"warning: the debug information found in \"/usr/lib/debug//lib64/libc-2.17.so.debug\" does not match \"/lib64/libc.so.6\" (CRC mismatch).\n"
INFO [ugdb::gdbmi::output] &"\n"
INFO [ugdb::gdbmi::output] &"warning: the debug information found in \"/usr/lib/debug/usr/lib64/libc-2.17.so.debug\" does not match \"/lib64/libc.so.6\" (CRC mismatch).\n"
INFO [ugdb::gdbmi::output] &"\n"
INFO [ugdb::gdbmi::output] &"warning: the debug information found in \"/usr/lib/debug//usr/lib64/libc-2.17.so.debug\" does not match \"/lib64/libc.so.6\" (CRC mismatch).\n"
INFO [ugdb::gdbmi::output] &"\n"
INFO [ugdb::gdbmi::output] &"warning: the debug information found in \"/usr/lib/debug/usr/lib64//libc-2.17.so.debug\" does not match \"/lib64/libc.so.6\" (CRC mismatch).\n"
INFO [ugdb::gdbmi::output] &"\n"
INFO [ugdb::gdbmi::output] =breakpoint-modified,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x0000000000400a95",func="main",file="/home/yliangsiew/Git/experiments/custom_malloc/main.c",fullname="/home/yliangsiew/Git/experiments/custom_malloc/main.c",line="8",thread-groups=["i1"],times="1",original-location="main"}
INFO [ugdb::gdbmi::output] ~"\nTemporary breakpoint "
INFO [ugdb::gdbmi::output] ~"1, main (argc=1, argv=0x7fffffffd1f8) at /home/yliangsiew/Git/experiments/custom_malloc/main.c:8\n"
INFO [ugdb::gdbmi::output] ~"8\t\tprintFreeList();\n"
INFO [ugdb::gdbmi::output] *stopped,reason="breakpoint-hit",disp="del",bkptno="1",frame={addr="0x0000000000400a95",func="main",args=[{name="argc",value="1"},{name="argv",value="0x7fffffffd1f8"}],file="/home/yliangsiew/Git/experiments/custom_malloc/main.c",fullname="/home/yliangsiew/Git/experiments/custom_malloc/main.c",line="8"},thread-id="1",stopped-threads="all",core="7"
INFO [ugdb::gdbmi::output] =breakpoint-deleted,id="1"
INFO [ugdb::gdbmi] Writing msg 2-stack-info-frame

INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi::output] 2^done,frame={level="0",addr="0x0000000000400a95",func="main",file="/home/yliangsiew/Git/experiments/custom_malloc/main.c",fullname="/home/yliangsiew/Git/experiments/custom_malloc/main.c",line="8"}
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 3-stack-info-depth

INFO [ugdb::gdbmi::output] 3^done,depth="1"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 4-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 13

INFO [ugdb::gdbmi::output] 4^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 5-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 13

INFO [ugdb::gdbmi::output] 5^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 6-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 13

INFO [ugdb::gdbmi::output] 6^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 7-data-disassemble -f /home/yliangsiew/Git/experiments/custom_malloc/main.c -l 8 -n -1 -- 4

INFO [ugdb::gdbmi::output] 7^error,msg="-data-disassemble: Mode argument must be 0, 1, 2, or 3."
INFO [ugdb::gdbmi::output] (gdb)
WARN [ugdb::tui::srcview] Failed to load assembly: GDB(MissingField("asm_insns", Object(Object { store: [("msg", String("-data-disassemble: Mode argument must be 0, 1, 2, or 3."), 0, 0)] })))
INFO [ugdb::gdbmi] Writing msg 8-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 13

INFO [ugdb::gdbmi::output] 8^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 9-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 13

INFO [ugdb::gdbmi::output] 9^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 10-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 13

INFO [ugdb::gdbmi::output] 10^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 11-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 13

INFO [ugdb::gdbmi::output] 11^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 12-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 13

INFO [ugdb::gdbmi::output] 12^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 13-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 13

INFO [ugdb::gdbmi::output] 13^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 14-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 15

INFO [ugdb::gdbmi::output] 14^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 15-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 18

INFO [ugdb::gdbmi::output] 15^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 16-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 20

INFO [ugdb::gdbmi::output] 16^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 17-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 21

INFO [ugdb::gdbmi::output] 17^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 18-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 23

INFO [ugdb::gdbmi::output] 18^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 19-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 26

INFO [ugdb::gdbmi::output] 19^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 20-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 27

INFO [ugdb::gdbmi::output] 20^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 21-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 29

INFO [ugdb::gdbmi::output] 21^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 22-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 30

INFO [ugdb::gdbmi::output] 22^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 23-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 31

INFO [ugdb::gdbmi::output] 23^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 24-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 31

INFO [ugdb::gdbmi::output] 24^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 25-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 28

INFO [ugdb::gdbmi::output] 25^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 26-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 26

INFO [ugdb::gdbmi::output] 26^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 27-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 25

INFO [ugdb::gdbmi::output] 27^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 28-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 24

INFO [ugdb::gdbmi::output] 28^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 29-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 23

INFO [ugdb::gdbmi::output] 29^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 30-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 21

INFO [ugdb::gdbmi::output] 30^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 31-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 20

INFO [ugdb::gdbmi::output] 31^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 32-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 20

INFO [ugdb::gdbmi::output] 32^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 33-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 19

INFO [ugdb::gdbmi::output] 33^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 34-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 18

INFO [ugdb::gdbmi::output] 34^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 35-break-insert --source /home/yliangsiew/Git/experiments/custom_malloc/main.c --line 17

INFO [ugdb::gdbmi::output] 35^error,msg="-break-insert: Unknown option ``-source''"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 36-thread-info

INFO [ugdb::gdbmi::output] 36^done,threads=[{id="1",target-id="Thread 0x7ffff7fc8740 (LWP 9273)",name="custom_malloc",frame={level="0",addr="0x0000000000400a95",func="main",args=[{name="argc",value="1"},{name="argv",value="0x7fffffffd1f8"}],file="/home/yliangsiew/Git/experiments/custom_malloc/main.c",fullname="/home/yliangsiew/Git/experiments/custom_malloc/main.c",line="8"},state="stopped",core="7"}],current-thread-id="1"
INFO [ugdb::gdbmi::output] (gdb)
INFO [ugdb::gdbmi] Writing msg 37-gdb-exit

INFO [ugdb::gdbmi::output] 37^exit
INFO [ugdb::gdbmi::output] =thread-exited,id="1",group-id="i1"
INFO [ugdb::gdbmi::output] =thread-group-exited,id="i1"
INFO [ugdb::tui::tui] unhandled async_record: [Notify, Thread(Exited)] {
  "id": "1",
  "group-id": "i1"
}
INFO [ugdb::tui::tui] unhandled async_record: [Notify, Thread(GroupExited)] {
  "id": "i1"
}
```

Source files are:
custom_malloc.h
```
#ifndef CUSTOM_MALLOC_H
#define CUSTOM_MALLOC_H

#include <stdint.h>

#define global static

/// This is the total size of the global memory pool.
#define kPoolSize 128

typedef uint8_t uint8;
typedef uint64_t uint64;


/// An entry in the global memory pool.
typedef struct FreeEntry
{
	void *begin;
	uint64 size;
} FreeEntry;


/**
 * A debug function that prints the contents of the current global free memory pool.
 */
void printFreeList();


/**
 * This is a **first-fit**-style custom ``malloc`` implementation.
 *  It uses a fixed pool size defined in ``kPoolSize`` and allocates the first
 * available free entry in a global pool that is of large enough size.
 *
 * @param size		The size to allocate.
 *
 * @return			A pointer to the newly-allocated memory.
 */
void* malloc(size_t size);


/**
 * This frees the memory previously allocated with ``malloc``. This **must** be
 * used together with the custom ``malloc`` implementation previously defined.
 *
 * @param ptr		The pointer to the memory region to de-allocate. This must have
 * 				been previously allocated with the custom ``malloc`` call.
 */
void free( void* ptr );


#endif /* CUSTOM_MALLOC_H */
```

custom_malloc.c
```
#include "custom_malloc.h"

global uint8 kMemoryPool[kPoolSize];
global uint64 kMemoryPoolUsed = 0;

// NOTE: (sonictk) This is just to point to the first entry in the free list to allocate from
global uint64 kFreeListUsed = 1;

global FreeEntry kFreeList[kPoolSize] = {&kMemoryPool, kPoolSize};

// NOTE: (sonictk) This is the size of the memory region to reserve for storing
// information about the size of each allocation.
global const uint8 kInfoSize = 8;


void printFreeList()
{
	// TODO: (sonictk) Debug
	printf("FREE LIST:\n");
	for (uint64 i=0; i < kFreeListUsed; ++i) {
		FreeEntry *entry = &kFreeList[i];
		printf("%p (%llu)\n", entry->begin, entry->size);
	}
}


FreeEntry *findFreeEntry(size_t size)
{
	// NOTE: (sonictk) Find the next available free entry large enough to allocate
	// the size requested
	FreeEntry *bestEntry = kFreeList;
	for (uint64 i=0; i < kFreeListUsed; ++i) {
		FreeEntry *entry = &kFreeList[i];
		if (entry->size >= size && entry->size < bestEntry->size) {
			bestEntry = entry;
		}
	}
	return bestEntry;
}


void *malloc(size_t size)
{
	// NOTE: (sonictk) The first ``kInfoSize`` bytes will be reserved for storing
	// the size of the allocation
	size += kInfoSize;

	FreeEntry *entry;
	entry = findFreeEntry(size);
	if (!entry) {
		return NULL;
	}

	void *basePtr;
	uint64 *sizePtr;
	void *result;

	basePtr = entry->begin;
	sizePtr = basePtr;
	result = (uint8 *)basePtr + kInfoSize;

	*sizePtr = size;

	entry->begin = (uint8 *)entry->begin + size;
	entry->size -= size;

	// TODO: (sonictk) Debug
	printFreeList();

	return result;
}


void free(void* ptr)
{
	FreeEntry *entry = &kFreeList[kFreeListUsed];

	void *basePtr = (uint8 *)ptr - kInfoSize;
	uint64 *sizePtr = basePtr;

	entry->begin = basePtr;
	entry->size = *sizePtr;

	kFreeListUsed++;

	// TODO: (sonictk) Debug
	printf("FREE\n");
	printFreeList();


}
```

 main.c
```
#include <stdio.h>
#include "custom_malloc.c"


int main(int argc, char *argv[])
{
	// TODO: (sonictk) Debug
	printFreeList();
	char *a = malloc(4 * sizeof(char));
	if (!a) {
		return -1;
	}
	char *b = malloc(4 * sizeof(char));
	char *c = malloc(4 * sizeof(char));

	printf("a: %p\n", a);
	printf("b: %p\n", b);
	printf("c: %p\n", c);

	free(b);

	char *d = malloc(4 * sizeof(char));
	printf("d: %p\n", d);

	free(a);
	free(c);
	free(d);

	printf("Finished program!\n");

	return 0;
}
```

**Comment by ftilde** [comment] 2020-03-13 22:05
Sorry for the late response, I was quite busy with work this week.

Indeed it looks like the gdb you are using is (too) old and does not support some of the gdbmi features that we currently use. In 5f69d9322cecae097f6d50995fe05ce9a25f9d5b I tried to switch both the breakpoint and disassembly commands to (I think) older and in the latter case now deprecated versions and they still work for me. Could have have another try and see if this works for you as well and if anything else is broken for you?

Unfortunately I wasn't quite able to infer from the changelog when which feature of the gdbmi protocol was added, so I cannot make a definite statement that we support "gdb version X and above" or similar. :(

**Comment by sonictk** [comment] 2020-03-13 22:18
@ftilde please, no apology required, you're under no obligation to do anything for me in the first place! And yes, I can imagine this week is a little crazy for everyone around the world, myself included

I will give that a shot; but I think most likely I will try to get around this by compiling a newer version of gdb from source and using that on my machines instead, if that is the solution.

Again, thank you for this tool and I really appreciate you taking the time to look at this issue!

**Comment by koutheir** [comment] 2020-03-19 21:29
@sonictk: Consider using the following `Makefile` to build a recent version of GDB.

Put the `Makefile` in its own directory (for example `gdb-9.1`), and use `make` to build GDB, then `make install` to install it locally inside the directory (to `gdb-9.1/install`). You don't have to install it on the system (in `/usr/local/bin/` for example) in order to use it, just run it from the `gdb-9.1/install/bin/x86_64-linux-gnu-gdb`.

I can confirm that this issue does not happen in `ugdb` with GDB version 9.1.

```Makefile
VERSION := 9.1
TARGET_TRIPLET := x86_64-linux-gnu

SRC_DIR := $(abspath ./gdb-$(VERSION))
SRC_TAR := $(abspath ./gdb-$(VERSION).tar.xz)
SRC_LINK := https://ftp.gnu.org/gnu/gdb/gdb-$(VERSION).tar.xz

BUILD_DIR := $(abspath ./build)
INSTALL_DIR := $(abspath ./install)

GDBSERVER_ENV := CFLAGS='-fpic' CXXFLAGS='-fpic' LDFLAGS='-static-libstdc++ -static-libgcc'

all: $(INSTALL_DIR)/bin/$(TARGET_TRIPLET)-gdb $(INSTALL_DIR)/bin/gdbserver

$(SRC_TAR):
	wget --output-document=$@.tmp '$(SRC_LINK)'
	mv '$@.tmp' '$@'

$(SRC_DIR): $(SRC_TAR)
	tar --extract --file=$<

$(INSTALL_DIR):
	mkdir --parents '$@'

$(INSTALL_DIR)/bin/$(TARGET_TRIPLET)-gdb: $(SRC_DIR) $(INSTALL_DIR)
	-rm --recursive --force $(BUILD_DIR)-gdb/* >/dev/null
	mkdir --parents $(BUILD_DIR)-gdb
	cd "$(BUILD_DIR)-gdb" && sh "$(SRC_DIR)/configure" --target=$(TARGET_TRIPLET) --prefix=$(INSTALL_DIR) --enable-compressed-debug-sections=all --enable-gold=no --enable-ld=no --enable-lto --enable-vtable-verify
	$(MAKE) -C '$(BUILD_DIR)-gdb'
	$(MAKE) -C '$(BUILD_DIR)-gdb' install

$(INSTALL_DIR)/bin/gdbserver: $(SRC_DIR) $(INSTALL_DIR) $(INSTALL_DIR)/bin/$(TARGET_TRIPLET)-gdb
	-rm --recursive --force $(BUILD_DIR)-gdbserver/* >/dev/null
	mkdir --parents $(BUILD_DIR)-gdbserver
	cd "$(BUILD_DIR)-gdbserver" && env $(GDBSERVER_ENV) sh "$(SRC_DIR)/gdb/gdbserver/configure" --host=$(TARGET_TRIPLET) --prefix=$(INSTALL_DIR)
	env $(GDBSERVER_ENV) $(MAKE) -C '$(BUILD_DIR)-gdbserver'
	env $(GDBSERVER_ENV) $(MAKE) -C '$(BUILD_DIR)-gdbserver' install

clean:
	-rm --recursive --force $(SRC_DIR) $(BUILD_DIR)-gdb $(BUILD_DIR)-gdbserver $(INSTALL_DIR) $(SRC_TAR)

clean-built:
	-rm --recursive --force $(SRC_DIR) $(BUILD_DIR)-gdb $(BUILD_DIR)-gdbserver $(INSTALL_DIR)

.PHONY: all clean
```

**Comment by ftilde** [comment] 2020-11-08 11:35
I'm closing this for now since the issue appears to be rather old gdb version (and may have been worked around, not sure).

**Closed by ftilde** 2020-11-08 11:35 UTC
